###
POST http://localhost:8080/api/comments/create
Content-Type: application/json

{
  "postID": 312,
  "text": "FrontEnd Test",
  "anonymous": false

}

###
GET http://localhost:8080/api/comments/post312

###
GET http://localhost:8080/api/comments/myPosts

###
PUT http://localhost:8080/api/comments/updateComment
Content-Type: application/json

{
  "postID":  287,
  "text":  "Comment Update vom FrontEnd"
}