
### find post based on id
GET http://localhost:8080/api/posts/find/7

### delete post based on id
DELETE http://localhost:8080/api/posts/delete/5

### get all posts based on author id
GET http://localhost:8080/api/posts/author/1

###
POST http://localhost:8080/api/posts/create
Content-Type: application/json

{
  "title": "findPost2",
  "text": "findPost2",
  "anonymous": false,
  "numberOfComments": 10
}